### PR TITLE
Try/catch errors when passing -impl and -intf flags

### LINKED ISSUE #336: Errors thrown from melange-compiler-libs not caught from melange
When calling `melc` with `-impl` flag, compilation errors are not propagated properly.

Repro:

```
$ cat > test.ml <<EOL
let age = My_lib.Arit.add 20 10
EOL
```

Without `-impl`, it works as expected:

```
$ melc -o test.cmj test.ml
File "test.ml", line 1, characters 10-25:
1 | let age = My_lib.Arit.add 20 10
              ^^^^^^^^^^^^^^^
Error: Unbound module My_lib
```

With `-impl` no error information is shown:

```
$ melc -o test.cmj -impl test.ml
melc: internal error, uncaught exception:
      Melange_compiler_libs.Env.Error(_)
```

The expected behaviour would be that when passing `-impl` flag, `melc` would show errors normally.

### PR DESCRIPTION
**Pull request by jchavarri**
Fixes #336.

Any processing done when passing `-impl` or `intf` flags is wrapped inside `try` statement, to reuse `Location.report_exception` for those cases too.

### CODE REVIEW

**Comment by anmonteiro** [comment]
Possibly a regression from https://github.com/melange-re/melange/pull/284
