### ISSUE TITLE
Failing to compile on switch 5.1.0

### ISSUE THREAD

**Issue by gborough** [melange-re/melange#1331]
```
[ERROR] The compilation of melange.5.0.0-51 failed at "dune build -p melange -j 19 @install".

#=== ERROR while compiling melange.5.0.0-51 ===================================#
# context     2.3.0 | linux/x86_64 | ocaml-base-compiler.5.1.0 | https://opam.ocaml.org#3f0fbcdd62029a20e3cefc8ce578e605f3bf22f8
# path        ~/.opam/test/.opam-switch/build/melange.5.0.0-51
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p melange -j 19 @install
# exit-code   1
# env-file    ~/.opam/log/melange-249166-a2fd36.env
# output-file ~/.opam/log/melange-249166-a2fd36.out
### output ###
# 45 |   let (name, sign) = (Compression.input_value ic : header) in
# [...]
# Error: Unbound module Compression
# (cd _build/default && /home/user/.opam/test/bin/ocamlc.opt -w -9 -g -bin-annot -I vendor/melange-compiler-libs/.melange_compiler_libs.objs/byte -I /home/user/.opam/test/lib/menhirLib -I /home/user/.opam/test/lib/ocaml/compiler-libs -I vendor/melange-compiler-libs/.melange_wrapper.objs/byte -intf-suffix .ml -no-alias-deps -open Melange_compiler_libs__ -o vendor/melange-compiler-libs/.melange_c[...]
# File "vendor/melange-compiler-libs/file_formats/cmt_format.ml", line 108, characters 20-43:
# 108 | let input_cmt ic = (Compression.input_value ic : cmt_infos)
#                           ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Compression
# (cd _build/default && /home/user/.opam/test/bin/ocamlopt.opt -w -9 -g -O3 -unbox-closures -I vendor/melange-compiler-libs/.melange_compiler_libs.objs/byte -I vendor/melange-compiler-libs/.melange_compiler_libs.objs/native -I /home/user/.opam/test/lib/menhirLib -I /home/user/.opam/test/lib/ocaml/compiler-libs -I vendor/melange-compiler-libs/.melange_wrapper.objs/byte -I vendor/melange-compiler[...]
# File "vendor/melange-compiler-libs/file_formats/cmi_format.ml", line 45, characters 22-45:
# 45 |   let (name, sign) = (Compression.input_value ic : header) in
#                            ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Compression
```

**Comment by anmonteiro** [comment]
That's fair, Melange only supports 5.1.1+. The reasoning is explained in this post: https://discuss.ocaml.org/t/ocaml-5-1-1-incoming-breaking-change-in-the-marshal-module/13457

I'll send an update to the opam-repository to account for this.

**Comment by anmonteiro** [comment]
https://github.com/ocaml/opam-repository/pull/27481
